"""Phase 2 — reproducible dataset audit (EXP-001 … EXP-006).

Runs every audit experiment registered in ``research/experiment_plan.md`` §2 and
writes a machine-readable record to ``artifacts/phase2_audit.json``. The findings
narrated in ``research/dataset_audit.md`` all come from this file, so every number
in the write-up can be regenerated by re-running this script.

The raw workbook is opened read-only and its checksum is verified before and
after (ADR-0003).

Usage
-----
    python scripts/run_data_audit.py
"""

from __future__ import annotations

import json
from typing import Any

import numpy as np
import pandas as pd
from scipy import stats

from edupro import config
from edupro.data.joins import build_interactions, course_popularity
from edupro.data.loader import load_all, sha256, verify_raw_workbook
from edupro.data.validation import validate
from edupro.evaluation.splits import (
    PROTOCOL_A_MIN_EVALUABLE,
    apply_global_split,
    global_temporal_split,
    leave_one_out_split,
    persist_split,
)
from edupro.features.learner import build_learner_features, summarise_features

RNG = np.random.default_rng(config.RANDOM_SEED)
N_PERMUTATIONS = 200


def gini(values: np.ndarray) -> float:
    """Gini coefficient of a non-negative array. 0 = perfectly even."""
    sorted_values = np.sort(np.asarray(values, dtype=float))
    n = len(sorted_values)
    if n == 0 or sorted_values.sum() == 0:
        return 0.0
    index = np.arange(1, n + 1)
    return float((2 * index - n - 1).dot(sorted_values) / (n * sorted_values.sum()))


def chi_square_uniform(counts: np.ndarray) -> dict[str, float]:
    chi2, p = stats.chisquare(np.asarray(counts, dtype=float))
    return {"chi2": round(float(chi2), 4), "dof": int(len(counts) - 1), "p_value": round(float(p), 6)}


def main() -> None:
    audit: dict[str, Any] = {}

    checksum_before = verify_raw_workbook()
    data = load_all()
    interactions = build_interactions(data, with_user_demographics=True, with_teacher=True)

    audit["provenance"] = {
        "workbook": config.RAW_WORKBOOK.name,
        "sha256": checksum_before,
        "seed": config.RANDOM_SEED,
        "n_permutations": N_PERMUTATIONS,
    }

    # ---------------------------------------------------------------- EXP-001
    report = validate(data)
    audit["EXP-001_validation"] = {
        "summary": report.summary(),
        "passed": report.ok,
        "findings": report.to_records(),
    }

    audit["sheet_profiles"] = {
        name: {
            "n_rows": int(len(frame)),
            "n_columns": int(frame.shape[1]),
            "duplicate_rows": int(frame.duplicated().sum()),
            "columns": {
                column: {
                    "dtype": str(frame[column].dtype),
                    "n_null": int(frame[column].isna().sum()),
                    "n_unique": int(frame[column].nunique()),
                }
                for column in frame.columns
            },
        }
        for name, frame in (
            (config.SHEET_USERS, data.users),
            (config.SHEET_TEACHERS, data.teachers),
            (config.SHEET_COURSES, data.courses),
            (config.SHEET_TRANSACTIONS, data.transactions),
        )
    }

    # ---------------------------------------------------------------- EXP-002
    merged = data.transactions.merge(
        data.courses[[config.KEY_COURSE, "CoursePrice"]], on=config.KEY_COURSE, how="left"
    )
    matches = np.isclose(merged["Amount"].astype(float), merged["CoursePrice"].astype(float))
    audit["EXP-002_amount_vs_price"] = {
        "n_transactions": int(len(merged)),
        "n_exact_matches": int(matches.sum()),
        "match_rate": round(float(matches.mean()), 6),
        "identical": bool(matches.all()),
        "n_distinct_amounts": int(data.transactions["Amount"].nunique()),
        "n_distinct_prices": int(data.courses["CoursePrice"].nunique()),
        "conclusion": (
            "Amount is identical to CoursePrice for every transaction. Spending "
            "features are therefore a deterministic function of which courses were "
            "taken, not an independent behavioural signal."
            if matches.all()
            else "Amount and CoursePrice differ on some transactions; characterise before use."
        ),
    }

    # ---------------------------------------------------------------- EXP-003
    counts = data.transactions.groupby(config.KEY_USER).size()
    distribution = counts.value_counts().sort_index()
    audit["EXP-003_sparsity"] = {
        "n_learners": int(len(counts)),
        "mean": round(float(counts.mean()), 4),
        "median": float(counts.median()),
        "std": round(float(counts.std()), 4),
        "min": int(counts.min()),
        "max": int(counts.max()),
        "distribution": {int(k): int(v) for k, v in distribution.items()},
        "n_with_1": int((counts == 1).sum()),
        "n_with_2": int((counts == 2).sum()),
        "n_with_3_plus": int((counts >= 3).sum()),
        "n_evaluable_loo": int((counts >= 2).sum()),
        "pct_with_1": round(float((counts == 1).mean() * 100), 2),
        "percentiles": {
            str(q): float(np.percentile(counts, q)) for q in (10, 25, 50, 75, 90, 95, 99)
        },
        "gini_user_activity": round(gini(counts.to_numpy()), 4),
        "empty_band": [int(n) for n in range(1, int(counts.max()) + 1) if n not in distribution.index],
        "cohort_light_1_to_4": {
            "n_learners": int((counts <= 4).sum()),
            "n_interactions": int(counts[counts <= 4].sum()),
        },
        "cohort_heavy_9_plus": {
            "n_learners": int((counts >= 9).sum()),
            "n_interactions": int(counts[counts >= 9].sum()),
        },
    }

    # ---------------------------------------------------------------- EXP-004
    split = global_temporal_split(interactions)
    frames = apply_global_split(interactions, split)
    loo = leave_one_out_split(interactions)
    split_path = persist_split(split, frames)
    audit["EXP-004_temporal_split"] = {
        **split.to_dict(),
        "threshold": PROTOCOL_A_MIN_EVALUABLE,
        "primary_protocol": "A (global temporal)" if split.protocol_a_viable else "B (leave-one-out)",
        "date_min": str(interactions[config.COL_TRANSACTION_DATE].min().date()),
        "date_max": str(interactions[config.COL_TRANSACTION_DATE].max().date()),
        "n_distinct_dates": int(interactions[config.COL_TRANSACTION_DATE].nunique()),
        "monthly_counts": {
            str(k): int(v)
            for k, v in interactions.groupby(
                interactions[config.COL_TRANSACTION_DATE].dt.to_period("M")
            ).size().items()
        },
        "leave_one_out": {
            "n_train": int(len(loo["train"])),
            "n_test": int(len(loo["test"])),
            "n_excluded_single_interaction": int(len(loo["excluded_single_interaction"])),
        },
        "persisted_to": str(split_path.relative_to(config.PROJECT_ROOT)),
    }

    # ---------------------------------------------------------------- EXP-005
    teachers_per_course = data.transactions.groupby(config.KEY_COURSE)[config.KEY_TEACHER].nunique()
    courses_per_teacher = data.transactions.groupby(config.KEY_TEACHER)[config.KEY_COURSE].nunique()
    pairs = data.transactions[[config.KEY_COURSE, config.KEY_TEACHER]].drop_duplicates()
    contingency = pd.crosstab(data.transactions[config.KEY_COURSE], data.transactions[config.KEY_TEACHER])
    chi2, p_value, dof, _ = stats.chi2_contingency(contingency)
    expertise = data.transactions.merge(
        data.teachers[[config.KEY_TEACHER, "Expertise"]], on=config.KEY_TEACHER
    ).merge(data.courses[[config.KEY_COURSE, "CourseCategory"]], on=config.KEY_COURSE)
    is_bijection = bool(teachers_per_course.max() == 1 and courses_per_teacher.max() == 1)
    audit["EXP-005_teacher_course_mapping"] = {
        "is_bijection": is_bijection,
        "exp_014_cancelled": is_bijection,
        "n_distinct_course_teacher_pairs": int(len(pairs)),
        "teachers_per_course": {
            "min": int(teachers_per_course.min()),
            "max": int(teachers_per_course.max()),
            "mean": round(float(teachers_per_course.mean()), 4),
        },
        "courses_per_teacher": {
            "min": int(courses_per_teacher.min()),
            "max": int(courses_per_teacher.max()),
            "mean": round(float(courses_per_teacher.mean()), 4),
        },
        "independence_chi2": {"chi2": round(float(chi2), 2), "dof": int(dof), "p_value": float(p_value)},
        "expertise_matches_category_rate": round(
            float((expertise["Expertise"] == expertise["CourseCategory"]).mean()), 6
        ),
        "expertise_match_random_expectation": round(1 / 12, 6),
    }

    # ---------------------------------------------------------------- EXP-006
    popularity = course_popularity(interactions)
    audit["EXP-006_distributions"] = {
        "course_popularity": {
            "min": int(popularity.min()),
            "max": int(popularity.max()),
            "mean": round(float(popularity.mean()), 4),
            "std": round(float(popularity.std()), 4),
            "gini": round(gini(popularity.to_numpy()), 4),
            "chi_square_uniform": chi_square_uniform(popularity.to_numpy()),
        },
        "uniformity_tests": {
            "users_age": chi_square_uniform(data.users["Age"].value_counts().sort_index().to_numpy()),
            "users_gender": chi_square_uniform(data.users["Gender"].value_counts().to_numpy()),
            "courses_per_category": chi_square_uniform(
                data.courses["CourseCategory"].value_counts().to_numpy()
            ),
            "courses_per_level": chi_square_uniform(
                data.courses["CourseLevel"].value_counts().to_numpy()
            ),
            "payment_method": chi_square_uniform(
                data.transactions["PaymentMethod"].value_counts().to_numpy()
            ),
            "transactions_per_day": chi_square_uniform(
                data.transactions.groupby(
                    data.transactions[config.COL_TRANSACTION_DATE].dt.date
                ).size().to_numpy()
            ),
        },
        "activity_overdispersion": {
            "mean": round(float(counts.mean()), 4),
            "variance": round(float(counts.var()), 4),
            "note": "Poisson would require mean == variance",
        },
    }

    # ------------------------------------------------- signal detection (EDA)
    audit["signal_detection"] = _signal_detection(data, interactions, counts)
    audit["behavioural_structure"] = _behavioural_structure(interactions, counts)

    # ------------------------------------------------------ feature candidates
    features = build_learner_features(interactions, users=data.users)
    summary = summarise_features(features)
    audit["feature_candidates"] = {
        "n_learners": int(len(features)),
        "n_features": int(features.shape[1]),
        "summary": json.loads(summary.to_json(orient="index")),
        "high_correlations": _high_correlations(features),
    }

    checksum_after = sha256(config.RAW_WORKBOOK)
    if checksum_after != checksum_before:
        raise RuntimeError("Raw workbook changed during the audit — immutability violated.")
    audit["provenance"]["sha256_after"] = checksum_after

    destination = config.ARTIFACTS_DIR / "phase2_audit.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(audit, indent=2, default=str), encoding="utf-8")

    _print_summary(audit, report)
    print(f"\nFull audit written to {destination.relative_to(config.PROJECT_ROOT)}")


def _signal_detection(data, interactions: pd.DataFrame, counts: pd.Series) -> dict[str, Any]:
    """Is there any learner-level preference signal beyond popularity?

    Each observed statistic is compared against a permutation null in which each
    learner's courses are redrawn from the empirical popularity distribution with
    that learner's history length held fixed. If the observed value sits inside
    the null interval, the data carries no preference signal on that dimension.
    """
    courses = data.courses.set_index(config.KEY_COURSE)
    popularity = interactions.groupby(config.KEY_COURSE).size().reindex(courses.index).fillna(0)
    probabilities = (popularity / popularity.sum()).to_numpy()
    category_of = courses["CourseCategory"].to_numpy()
    level_of = courses["CourseLevel"].to_numpy()
    type_of = courses["CourseType"].to_numpy()
    position = {course: i for i, course in enumerate(courses.index)}

    by_user = interactions.groupby(config.KEY_USER)[config.KEY_COURSE].apply(list)
    observed_idx = [np.array([position[c] for c in lst]) for lst in by_user]
    lengths = np.array([len(x) for x in observed_idx])

    def statistics(draws: list[np.ndarray]) -> tuple[float, float, float, float]:
        distinct_categories, top_share, distinct_levels, free_share = [], [], [], []
        for draw in draws:
            categories = category_of[draw]
            _, category_counts = np.unique(categories, return_counts=True)
            distinct_categories.append(len(category_counts))
            top_share.append(category_counts.max() / len(draw))
            distinct_levels.append(len(set(level_of[draw])))
            free_share.append((type_of[draw] == "Free").mean())
        return (
            float(np.mean(distinct_categories)),
            float(np.mean(top_share)),
            float(np.mean(distinct_levels)),
            float(np.mean(free_share)),
        )

    names = ("mean_distinct_categories", "mean_top_category_share",
             "mean_distinct_levels", "mean_free_share")
    observed = statistics(observed_idx)
    null = np.array([
        statistics([
            RNG.choice(len(courses), size=n, replace=False, p=probabilities) for n in lengths
        ])
        for _ in range(N_PERMUTATIONS)
    ])

    preference = {}
    for i, name in enumerate(names):
        low, high = np.percentile(null[:, i], [2.5, 97.5])
        preference[name] = {
            "observed": round(observed[i], 6),
            "null_mean": round(float(null[:, i].mean()), 6),
            "null_ci_95": [round(float(low), 6), round(float(high), 6)],
            "z": round(float((observed[i] - null[:, i].mean()) / null[:, i].std()), 4),
            "signal": bool(observed[i] < low or observed[i] > high),
        }

    # Demographic association with choice.
    demographic = {}
    age_band = pd.cut(interactions["Age"], bins=[14, 20, 25, 30, 35])
    for label, left, right in (
        ("gender_x_category", interactions["Gender"], interactions["CourseCategory"]),
        ("gender_x_level", interactions["Gender"], interactions["CourseLevel"]),
        ("ageband_x_category", age_band, interactions["CourseCategory"]),
        ("ageband_x_level", age_band, interactions["CourseLevel"]),
    ):
        chi2, p_value, dof, _ = stats.chi2_contingency(pd.crosstab(left, right))
        demographic[label] = {
            "chi2": round(float(chi2), 4),
            "dof": int(dof),
            "p_value": round(float(p_value), 6),
            "dependent": bool(p_value < 0.05),
        }

    # Teacher concentration, against a null that draws a teacher at random from
    # those actually attached to each course the learner took.
    multi = counts[counts >= 2].index
    teachers_per_user = interactions.groupby(config.KEY_USER)[config.KEY_TEACHER].nunique()
    observed_ratio = float((teachers_per_user[multi] / counts[multi]).mean())
    pairs = interactions[[config.KEY_COURSE, config.KEY_TEACHER]].drop_duplicates()
    teacher_pool = pairs.groupby(config.KEY_COURSE)[config.KEY_TEACHER].apply(list).to_dict()
    histories = interactions[interactions[config.KEY_USER].isin(multi)].groupby(
        config.KEY_USER
    )[config.KEY_COURSE].apply(list)
    null_ratios = []
    for _ in range(30):
        per_user = [
            len({RNG.choice(teacher_pool[c]) for c in history}) / len(history)
            for history in histories
        ]
        null_ratios.append(float(np.mean(per_user)))

    return {
        "preference_vs_popularity_null": preference,
        "demographics_vs_choice": demographic,
        "teacher_concentration": {
            "observed_distinct_teachers_per_interaction": round(observed_ratio, 6),
            "null_mean": round(float(np.mean(null_ratios)), 6),
            "null_ci_95": [
                round(float(np.percentile(null_ratios, 2.5)), 6),
                round(float(np.percentile(null_ratios, 97.5)), 6),
            ],
            "signal": bool(observed_ratio < np.percentile(null_ratios, 2.5)),
        },
    }


def _behavioural_structure(interactions: pd.DataFrame, counts: pd.Series) -> dict[str, Any]:
    """Characterise the structure that *does* exist: cohorts, teacher reuse, progression.

    The teacher signal is real but must be described precisely: learners repeat
    instructors far more than chance, yet that barely narrows which *course* comes
    next, because each teacher covers roughly a quarter of the catalogue.
    """
    multi = counts[counts >= 2].index
    heavy = counts[counts >= 9].index
    light_multi = counts[(counts >= 2) & (counts <= 4)].index
    teachers_per_user = interactions.groupby(config.KEY_USER)[config.KEY_TEACHER].nunique()

    # Does knowing a learner's prior teachers predict their next course?
    pairs = interactions[[config.KEY_COURSE, config.KEY_TEACHER]].drop_duplicates()
    courses_of_teacher = pairs.groupby(config.KEY_TEACHER)[config.KEY_COURSE].apply(set).to_dict()
    hits = total = 0
    pool_sizes: list[int] = []
    unseen_sizes: list[int] = []
    n_courses = interactions[config.KEY_COURSE].nunique()
    for _, group in interactions[interactions[config.KEY_USER].isin(multi)].groupby(
        config.KEY_USER
    ):
        history, held_out = group.iloc[:-1], group.iloc[-1]
        pool = set().union(
            *[courses_of_teacher[t] for t in history[config.KEY_TEACHER]]
        ) - set(history[config.KEY_COURSE])
        pool_sizes.append(len(pool))
        unseen_sizes.append(n_courses - history[config.KEY_COURSE].nunique())
        total += 1
        hits += int(held_out[config.KEY_COURSE] in pool)
    hit_rate = hits / total
    chance = float(np.mean(pool_sizes) / np.mean(unseen_sizes))

    # Do learners progress from easier to harder courses over time?
    slopes = []
    for _, group in interactions[interactions[config.KEY_USER].isin(multi)].groupby(
        config.KEY_USER
    ):
        if len(group) >= 3 and group["LevelOrdinal"].nunique() > 1:
            slopes.append(np.polyfit(np.arange(len(group)), group["LevelOrdinal"].to_numpy(), 1)[0])
    slope_t, slope_p = stats.ttest_1samp(slopes, 0.0) if slopes else (float("nan"), float("nan"))

    gaps = (
        interactions[interactions[config.KEY_USER].isin(multi)]
        .groupby(config.KEY_USER)[config.COL_TRANSACTION_DATE]
        .diff().dt.days.dropna()
    )

    def cohort_summary(index) -> dict[str, float]:
        subset = interactions[interactions[config.KEY_USER].isin(index)]
        return {
            "n_learners": int(len(index)),
            "n_interactions": int(len(subset)),
            "free_share": round(float(subset["IsFree"].mean()), 4),
            "mean_course_rating": round(float(subset["CourseRating"].mean()), 4),
            "mean_level_ordinal": round(float(subset["LevelOrdinal"].mean()), 4),
            "mean_age": round(float(subset.groupby(config.KEY_USER)["Age"].first().mean()), 4),
        }

    return {
        "cohorts": {
            "light_1_to_4": cohort_summary(counts[counts <= 4].index),
            "heavy_9_to_16": cohort_summary(heavy),
        },
        "teacher_reuse": {
            "distinct_teachers_per_learner_mean": round(float(teachers_per_user[multi].mean()), 4),
            "interactions_per_learner_mean": round(float(counts[multi].mean()), 4),
            "heavy_cohort_distinct_teachers_mean": round(float(teachers_per_user[heavy].mean()), 4),
            "heavy_cohort_interactions_mean": round(float(counts[heavy].mean()), 4),
            "light_multi_ratio": round(float((teachers_per_user[light_multi] / counts[light_multi]).mean()), 4),
            "heavy_ratio": round(float((teachers_per_user[heavy] / counts[heavy]).mean()), 4),
        },
        "teacher_predicts_next_course": {
            "n_learners": int(total),
            "mean_pool_size": round(float(np.mean(pool_sizes)), 4),
            "mean_unseen_courses": round(float(np.mean(unseen_sizes)), 4),
            "hit_rate": round(hit_rate, 6),
            "chance_rate": round(chance, 6),
            "lift": round(hit_rate / chance, 4),
            "note": (
                "Teacher reuse is strong, but each teacher covers ~25 of ~55 unseen "
                "courses, so it barely narrows which course comes next."
            ),
        },
        "level_progression": {
            "n_learners": len(slopes),
            "mean_slope": round(float(np.mean(slopes)), 6) if slopes else None,
            "t": round(float(slope_t), 4),
            "p_value": round(float(slope_p), 6),
            "progression": bool(slope_p < 0.05) if slopes else False,
        },
        "inter_purchase_gap_days": {
            "mean": round(float(gaps.mean()), 4),
            "median": float(gaps.median()),
            "max": int(gaps.max()),
            "same_day_share": round(float((gaps == 0).mean()), 6),
        },
    }


def _high_correlations(features: pd.DataFrame, threshold: float = 0.8) -> list[dict[str, Any]]:
    numeric = features.select_dtypes(include=[np.number])
    matrix = numeric.corr()
    out = []
    columns = list(matrix.columns)
    for i, a in enumerate(columns):
        for b in columns[i + 1:]:
            r = matrix.loc[a, b]
            if pd.notna(r) and abs(r) >= threshold:
                out.append({"a": a, "b": b, "r": round(float(r), 4)})
    return sorted(out, key=lambda d: -abs(d["r"]))


def _print_summary(audit: dict[str, Any], report) -> None:
    print("=" * 76)
    print("PHASE 2 DATA AUDIT")
    print("=" * 76)
    print(f"\nEXP-001 validation : {report.summary()}  -> {'PASS' if report.ok else 'FAIL'}")
    for finding in report.findings:
        print(f"    {finding}")

    e2 = audit["EXP-002_amount_vs_price"]
    print(f"\nEXP-002 Amount==CoursePrice : {e2['match_rate']*100:.2f}% of rows  "
          f"-> identical={e2['identical']}")

    e3 = audit["EXP-003_sparsity"]
    print(f"\nEXP-003 sparsity   : mean={e3['mean']} median={e3['median']} max={e3['max']}")
    print(f"    1 interaction : {e3['n_with_1']} ({e3['pct_with_1']}%)")
    print(f"    2 interactions: {e3['n_with_2']}")
    print(f"    3+            : {e3['n_with_3_plus']}")
    print(f"    empty bands   : {e3['empty_band']}")

    e4 = audit["EXP-004_temporal_split"]
    print(f"\nEXP-004 split      : V={e4['validation_date']} T={e4['test_date']}")
    print(f"    evaluable learners={e4['n_evaluable_learners']} (threshold {e4['threshold']}) "
          f"-> primary protocol {e4['primary_protocol']}")

    e5 = audit["EXP-005_teacher_course_mapping"]
    print(f"\nEXP-005 teacher map: bijection={e5['is_bijection']} "
          f"pairs={e5['n_distinct_course_teacher_pairs']} "
          f"-> EXP-014 cancelled={e5['exp_014_cancelled']}")

    e6 = audit["EXP-006_distributions"]["course_popularity"]
    print(f"\nEXP-006 popularity : min={e6['min']} max={e6['max']} gini={e6['gini']} "
          f"chi2-uniform p={e6['chi_square_uniform']['p_value']}")

    print("\nSignal detection (observed vs popularity-matched permutation null):")
    for name, result in audit["signal_detection"]["preference_vs_popularity_null"].items():
        print(f"    {name:<28} obs={result['observed']:.4f} null={result['null_mean']:.4f} "
              f"z={result['z']:+.2f}  {'SIGNAL' if result['signal'] else 'no signal'}")
    tc = audit["signal_detection"]["teacher_concentration"]
    print(f"    teacher concentration        obs={tc['observed_distinct_teachers_per_interaction']:.4f} "
          f"null={tc['null_mean']:.4f}  {'SIGNAL' if tc['signal'] else 'no signal'}")


if __name__ == "__main__":
    main()
